### PR TITLE
Update Bisection Task with Dynanometer.sce

### PR DESCRIPTION
**Pull request by Zhenna**

### CODE REVIEW

**Comment by emailyc** [comment]
Why does `sound_label_event` have `port_code` set to 1?

**Comment by Zhenna** [comment]
The dynamometer was assigned to port number 1. XQ said we can only send 1~3 as triggers (port codes) to the port device, which is the dynamometer in this case. So I assigned 3 as port code for instruction trials. I wanted to send a trigger when the experiment starts, but did not know how. The sound_label_event was also assigned a port_code, so during every trial, Presentation will send a trigger to dynamometer. This is what I am trying to do, but not sure if I have done it correctly.

**Comment by emailyc** [comment]
I believe the `port_code` for every stimulus trial is already implemented in `play_sound_trial` where it gets a `short_port` if the sound index is equal to or lower than 4; `long_port` otherwise. 
The number of the two ports are defined in Participant Number.pcl

**Comment by Zhenna** [comment]
Ok. Then the redundant port_code should be removed.

**Comment by Zhenna** [comment]
What is the purpose of play_break_trial( "BREAK" ) in loop i of Practice_Block.pcl?

**Comment by emailyc** [comment]
for now we are looping the 7 different durations 3 times. `play_break_trial( "BREAK" )` shows a screen for participant to take a break in between these 3 loops.

**Comment by Zhenna** [comment]
I don't think it is necessary to have breaks during practice, but if you think it is helpful for the subject to learn, then leave it there.

**Comment by Zhenna** [comment]
instruct_event.set_event_code( 
		"Stim;" +
		logfile.subject() + ";" +
		"Instruction" + ";" +
		"Instruction" + ";" +
		"Instruction" + ";" +
		"Instruction" 
	);


instruct_event was not defined

**Comment by emailyc** [comment]
my bad, i pushed an old copy of the scenario file. guess i should start using branches. 😅

**Pull request closed without merging**
